credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      phone_number: 111111111
      password: abc # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      phone_number: 11111112
      password: def # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com