version: '3.9'

services:
  postgres:
    networks:
      - medai
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app

  app:
    networks:
      - medai
    build:
      context: ./backend
    ports:
      - "9090:9090"
    depends_on:
      - postgres

#  frontend:
#    networks:
#      - fileShare_net
#    build:
#      context: ./views
#    ports:
#      - "5321:8501"
#    depends_on:
#      - postgres
#      - app


networks:
  medai:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.0.157.0/24
